### ISSUE TITLE
Market SAT hatası

### ISSUE THREAD

**Issue by EUA** [outlier-1/btcturkapi-python#4]
Market SAT da sorun var.
Satış BTC ile yapılıyor, fakat bakiyede yeterince BTC yok ise bu şekil bir hata veriyor bakiye yetersiz hatası vereceğine.

```
>>> btr.api.submit_market_order(quantity=1,order_type='sell',pair_symbol='BTCUSDT')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.8/site-packages/btcturk_api/properties.py", line 11, in wrapper_decorator
    value = func(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/btcturk_api/client.py", line 700, in submit_market_order
    return self.submit_order(params)
  File "/usr/lib/python3.8/site-packages/btcturk_api/properties.py", line 11, in wrapper_decorator
    value = func(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/btcturk_api/client.py", line 831, in submit_order
    return self._post(request_url, params)
  File "/usr/lib/python3.8/site-packages/btcturk_api/client.py", line 237, in _post
    return response.json()['data']
KeyError: 'data'
```

**Comment by outlier-1** [comment]
Merhaba, şimdi o problemi çözüp yeni 1.0.1 versiyonunu yayınladım. Artık karşılaştığınız durumda InvalidRequestParameterError hatası verip API'nin bakiyenin yetersiz veya başka bir emirden dolayı kilitli olduğu durumda yolladığı orjinal mesajı olan FAILED_ORDER_WITH_OPEN_ORDERS mesajını gösteriyor.

Daha detaylı bilgiler içermesi için önümüzdeki günlerde eklemeler yapacağım.

Yayınladığım yeni versiyonu kullanmak için python paketini güncellemeniz gerekmektedir.

Linuxta aşağıdaki komutu kullanabilirsiniz.
sudo pip install btcturk_api --upgrade

**Comment by EUA** [comment]
Hızlı debug için teşekkürler.
